In [4]:
import os
import pandas as pd
import matplotlib as plt

In [5]:
data = pd.read_csv("Train.csv")
copy_data = data
print("first 5 rows: ")
display(data.head())
print("==============================================================================")
print("last 5 rows:")
data.tail()

first 5 rows:

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30

==============================================================================
last 5 rows:

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
45588,0x7c09,JAPRES04DEL01,30,4.8,26.902328,75.794257,26.912328,75.804257,24-03-2022,11:35:00,11:45:00,conditions Windy,High,1,Meal,motorcycle,0,No,Metropolitian,(min) 32
45589,0xd641,AGRRES16DEL01,21,4.6,0.000000,0.000000,0.070000,0.070000,16-02-2022,19:55:00,20:10:00,conditions Windy,Jam,0,Buffet,motorcycle,1,No,Metropolitian,(min) 36
45590,0x4f8d,CHENRES08DEL03,30,4.9,13.022394,80.242439,13.052394,80.272439,11-03-2022,23:50:00,00:05:00,conditions Cloudy,Low,1,Drinks,scooter,0,No,Metropolitian,(min) 16
45591,0x5eee,COIMBRES11DEL01,20,4.7,11.001753,76.986241,11.041753,77.026241,07-03-2022,13:35:00,13:40:00,conditions Cloudy,High,0,Snack,motorcycle,1,No,Metropolitian,(min) 26
45592,0x5fb2,RANCHIRES09DEL02,23,4.9,23.351058,85.325731,23.431058,85.405731,02-03-2022,17:10:00,17:15:00,conditions Fog,Medium,2,Snack,scooter,1,No,Metropolitian,(min) 36

In [6]:
print(f"number of observations (rows): {data.shape[0]}")
print(f"number of observations (features): {data.shape[1]}\n")


print(f"general information: {data.info()}")

number of observations (rows): 45593
number of observations (features): 20

<class 'pandas.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  str
 1   Delivery_person_ID           45593 non-null  str
 2   Delivery_person_Age          45593 non-null  str
 3   Delivery_person_Ratings      45593 non-null  str
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  str
 9   Time_Orderd                  45593 non-null  str
 10  Time_Order_picked            45593 non-null  str
 11  Weatherconditions            45593 non-null  str
 12  Road_traffic_density         45593 non-null  str
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  str
 15  Type_of_vehicle              45593 non-null  str
 16  multiple_deliveries          45593 non-null  str
 17  Festival                     45593 non-null  str
 18  City                         45593 non-null  str
 19  Time_taken(min)              45593 non-null  str
dtypes: float64(4), int64(1), str(15)
memory usage: 7.0 MB
general information: None

In [7]:
data.isna().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
dtype: int64

In [9]:
for column in data.select_dtypes(include=["object", "string"]).columns:
    print(f"--- {column} ---")
    print(data[column].unique())
    print("\n") # Adds a space between columns

--- ID ---
<StringArray>
['0x4607 ', '0xb379 ', '0x5d6d ', '0x7a6a ', '0x70a2 ', '0x9bb4 ', '0x95b4 ',
 '0x9eb2 ', '0x1102 ', '0xcdcd ',
 ...
 '0x5193 ', '0xa333 ', '0xc9ab ', '0x4e21 ', '0x1178 ', '0x7c09 ', '0xd641 ',
 '0x4f8d ', '0x5eee ', '0x5fb2 ']
Length: 45593, dtype: str


--- Delivery_person_ID ---
<StringArray>
[  'INDORES13DEL02 ',   'BANGRES18DEL02 ',   'BANGRES19DEL01 ',
  'COIMBRES13DEL02 ',   'CHENRES12DEL01 ',    'HYDRES09DEL03 ',
 'RANCHIRES15DEL01 ',    'MYSRES15DEL02 ',    'HYDRES05DEL02 ',
    'DEHRES17DEL01 ',
 ...
    'KNPRES18DEL01 ',    'BHPRES08DEL03 ',   'AURGRES13DEL01 ',
   'LUDHRES03DEL02 ',    'KNPRES05DEL01 ',    'GOARES01DEL03 ',
    'KOCRES08DEL03 ',    'KOCRES04DEL01 ',    'BHPRES06DEL03 ',
    'GOARES03DEL03 ']
Length: 1320, dtype: str


--- Delivery_person_Age ---
<StringArray>
[  '37',   '34',   '23',   '38',   '32',   '22',   '33',   '35',   '36',
   '21',   '24',   '29',   '25',   '31',   '27',   '26',   '20', 'NaN ',
   '28',   '39',   '30',   '15',   '50']
Length: 23, dtype: str


--- Delivery_person_Ratings ---
<StringArray>
[ '4.9',  '4.5',  '4.4',  '4.7',  '4.6',  '4.8',  '4.2',  '4.3',    '4',
  '4.1',    '5',  '3.5', 'NaN ',  '3.8',  '3.9',  '3.7',  '2.6',  '2.5',
  '3.6',  '3.1',  '2.7',    '1',  '3.2',  '3.3',    '6',  '3.4',  '2.8',
  '2.9',    '3']
Length: 29, dtype: str


--- Order_Date ---
<StringArray>
['19-03-2022', '25-03-2022', '05-04-2022', '26-03-2022', '11-03-2022',
 '04-03-2022', '14-03-2022', '20-03-2022', '12-02-2022', '13-02-2022',
 '14-02-2022', '02-04-2022', '01-03-2022', '16-03-2022', '15-02-2022',
 '10-03-2022', '27-03-2022', '12-03-2022', '01-04-2022', '05-03-2022',
 '11-02-2022', '08-03-2022', '03-04-2022', '30-03-2022', '28-03-2022',
 '18-03-2022', '06-04-2022', '04-04-2022', '24-03-2022', '09-03-2022',
 '02-03-2022', '13-03-2022', '29-03-2022', '31-03-2022', '17-03-2022',
 '07-03-2022', '15-03-2022', '16-02-2022', '03-03-2022', '18-02-2022',
 '23-03-2022', '17-02-2022', '06-03-2022', '21-03-2022']
Length: 44, dtype: str


--- Time_Orderd ---
<StringArray>
['11:30:00', '19:45:00', '08:30:00', '18:00:00', '13:30:00', '21:20:00',
 '19:15:00', '17:25:00', '20:55:00', '21:55:00',
 ...
 '13:15:00', '14:00:00', '15:40:00', '16:25:00', '14:10:00', '13:45:00',
 '13:55:00', '14:35:00', '16:30:00', '14:45:00']
Length: 177, dtype: str


--- Time_Order_picked ---
<StringArray>
['11:45:00', '19:50:00', '08:45:00', '18:10:00', '13:45:00', '21:30:00',
 '19:30:00', '17:30:00', '21:05:00', '22:10:00',
 ...
 '17:10:00', '15:25:00', '14:20:00', '12:35:00', '14:00:00', '14:10:00',
 '14:55:00', '13:15:00', '14:50:00', '16:00:00']
Length: 193, dtype: str


--- Weatherconditions ---
<StringArray>
[     'conditions Sunny',     'conditions Stormy', 'conditions Sandstorms',
     'conditions Cloudy',        'conditions Fog',      'conditions Windy',
        'conditions NaN']
Length: 7, dtype: str


--- Road_traffic_density ---
<StringArray>
['High ', 'Jam ', 'Low ', 'Medium ', 'NaN ']
Length: 5, dtype: str


--- Type_of_order ---
<StringArray>
['Snack ', 'Drinks ', 'Buffet ', 'Meal ']
Length: 4, dtype: str


--- Type_of_vehicle ---
<StringArray>
['motorcycle ', 'scooter ', 'electric_scooter ', 'bicycle ']
Length: 4, dtype: str


--- multiple_deliveries ---
<StringArray>
['0', '1', '3', 'NaN ', '2']
Length: 5, dtype: str


--- Festival ---
<StringArray>
['No ', 'Yes ', 'NaN ']
Length: 3, dtype: str


--- City ---
<StringArray>
['Urban ', 'Metropolitian ', 'Semi-Urban ', 'NaN ']
Length: 4, dtype: str


--- Time_taken(min) ---
<StringArray>
['(min) 24', '(min) 33', '(min) 26', '(min) 21', '(min) 30', '(min) 40',
 '(min) 32', '(min) 34', '(min) 46', '(min) 23', '(min) 20', '(min) 41',
 '(min) 15', '(min) 36', '(min) 39', '(min) 18', '(min) 38', '(min) 47',
 '(min) 12', '(min) 22', '(min) 25', '(min) 35', '(min) 10', '(min) 19',
 '(min) 11', '(min) 28', '(min) 52', '(min) 16', '(min) 27', '(min) 49',
 '(min) 17', '(min) 14', '(min) 37', '(min) 44', '(min) 42', '(min) 31',
 '(min) 13', '(min) 29', '(min) 50', '(min) 43', '(min) 48', '(min) 54',
 '(min) 53', '(min) 45', '(min) 51']
Length: 45, dtype: str

* we have white spaces in most of the columns we should strip them first

In [ ]:
for colum in data.select_dtypes(include="str").columns: